### ISSUE TITLE
"Произошла ошибка. Время соединения истекло"

### ISSUE THREAD

**Issue by pro100valera** [Aserus/spruthub-pik-script#1]
При сохранении сценария для получения токенов такая ошибка появлялась в течение 5 минут, но потом проскочило.
После добавления полученных из логов констант ошибка снова вернулась и не даёт сохранить сценарий и перейти к созданию аксессуара, потому что вылезает эта ошибка и хаб считает сценарий несохраненным.

Возможно, какая-то защита на стороне ПИКа? Или частота запросов? Победить пока не смог.

**Comment by Aserus** [comment]
Я тоже такое ловил. Можно конечно увеличить время ожидание - практика показывает что то не поможет.
Я подозреваю что это не защита, а проблема с самими сервера. По сути мы в обоих случаях ничего не можем сделать.

**Comment by Aserus** [comment]
Я тоже такое ловил. В основном в час пик(с 18:00 по 21:00). Можно конечно увеличить время ожидание - но практика показывает что это не поможет.
Я подозреваю что это не защита, а проблема с самими сервера. По сути мы в обоих случаях ничего не можем сделать.

**Comment by pro100valera** [comment]
Печально( Я пробовал не в час-пик, а ночью.
Кстати, чисто из замеченного, в константах, наверное, стоит как-то произвольно менять API_DEVICE_CLIENT, а то бедный "телефон Альфреда" будет светиться у ПИКа на разных квартирах в разных ЖК.

**Comment by Aserus** [comment]
Альфред это скорей тип клиента, а не конкретный id. Предполагаю что на андроиде тот же альфред)

**Comment by pro100valera** [comment]
Мне кажется, что это суть имя устройства)) Подозреваю, что реверс делался с телефона, принадлежащего Альфреду. Даже предполагаю, которому именно)

**Comment by Aserus** [comment]
Да, реверс был с айфона и владельца точно звали не Альфред))
По endpoint тут можно увидеть что это скорей тип
https://iot.rubetek.com/api/**alfred**/v1/
